import LanguageSwitcher from "@/components/LanguageSwitcher";
import { useTranslations } from "next-intl";
import Head from "next/head";
import { useRouter } from "next/navigation";

export default function Home() {
  const t = useTranslations();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Next-intl v4</h1>
        <h1>{t("welcome")}</h1>
        <LanguageSwitcher />
        <button onClick={() => router.push("/posts/1")}>go</button>
      </div>
    </>
  );
}
